---
title: "Examen Diagnóstico"
author: "Felipe Pérez Vargas"
date: "9/2/2021"
output:
  pdf_document: default
  html_document: default
---

### Resuelve los siguientes ejercicios:

1.- Mediante el uso de eliminación Gaussiana encuentre los valores de: $x_{1}$, $x_{2}$ y $x_{3}$

\begin{eqnarray*}
   5x_1 - 2x_2 + x_3&=&24\\
   2x_1 + 5x_2 - 2x_3&=&-14\\
   x_1 - 4x_2 + 3x_3&=&26
\end{eqnarray*}
 
 _________________________________________________________________________
 
2.- Mediante el uso de la eliminació, Gauss-Jordan encuentre los valores de: 
$x_{1}$, $x_{2}$ y $x_{3}$


\begin{eqnarray*}
   x_1 - 3x_2 + 2x_3&=&-3\\
  5x_1 + 6x_2 -  x_3&=&13\\
  4x_1 -  x_2 + 3x_3&=&8
\end{eqnarray*}
___________________________________________________________________________

3.- Encuentre el determinande de la siguiente matriz 

\begin{equation}
\begin{bmatrix}
1 & -2 & 1\\
2 &  5 &-2\\
1 & -4 & 3
\end{bmatrix}
\end{equation}
________________________________________________________________________

4.- Encuentre la inversa de la siguiente matriz 

\begin{equation}
\begin{bmatrix}
1 & -3 & 2\\
5 &  6 &-1\\
4 & -1 & 3
\end{bmatrix}
\end{equation}

___________________________________________________________________________


5.- Mediante el método grafico encuentre la solución al sistema de ecuaciones en el dominio de $x_{1}=[-3,7]$ y $x_{2}=[-3,7]$


\begin{eqnarray*}
   x_1 + 3x_2 &=&6\\
  2x_1 - x_2 &=&5\\
  3x_{1}+2x_{2}&=&11
\end{eqnarray*}

______________________________________________________________________________

6.- Encuentra las raíces de la siguiente función: 

$f(x)=4x^{2}-12x+9=0$

______________________________________________________________________________

7.- Encuentre la deriva de la siguiente función: 


$f(x)=\frac{2x^{4}+3x^{2}}{2x^{3}-6x^{2}}$

_______________________________________________________________________________


8.- Realiza la integral de la siguiente función:


$f(x)=\int_{1}^{2}(\sqrt{2x}+\sqrt[3]{x})dx$


_______________________________________________________________________________











